### ISSUE TITLE
Array to string conversion in CSV report

### ISSUE THREAD

**Issue by robingram** [silverstripe/silverstripe-securityreport#16]
For reference, this extension replicates framework code that has a bug as described in issue [#6617](https://github.com/silverstripe/silverstripe-framework/issues/6617) and fixed in PR [#6622](https://github.com/silverstripe/silverstripe-framework/pull/6622).

When I get the chance I'll put in a PR for the fix, hopefully today.

**Comment by robingram** [comment]
I have a PR ready to go. Which branch would you like me to target?

**Comment by robbieaverill** [comment]
@robingram the branch alias for this module is still at 1.0.x-dev in master, but since there's a `1` branch perhaps you should PR against that :)

**Comment by robingram** [comment]
Created PR #18

**Comment by robbieaverill** [comment]
Fixed in #18. Thanks @robingram
