### ISSUE TITLE
Check and update module for SS4 compatibility where necessary

### ISSUE THREAD

**Issue by rupachup** [silverstripe/silverstripe-securityreport#27]
## Acceptance Criteria

- [x] Module works on SS4
- [x] Beta tag released

## Pull requests

- [x] https://github.com/silverstripe/silverstripe-securityreport/pull/28
- [x] https://github.com/silverstripe/silverstripe-securityreport/pull/29

**Comment by robbieaverill** [comment]
https://github.com/silverstripe/silverstripe-securityreport/releases/tag/2.0.0-beta1
