### ISSUE TITLE
Missing columns in report

### ISSUE THREAD

**Issue by raissanorth** [silverstripe/silverstripe-securityreport#32]
The security report no longer contains the columns showing the date and time of the last visit. Were these intentionally removed?

This affects:
 
```
silverstripe/securityreport               dev-master 24a71d6

silverstripe/framework                    4.1.x-dev 9ed3cd4
silverstripe/cms                          4.1.x-dev 7dea009
silverstripe/reports                      4.1.x-dev ac23686
```

Compare against e.g.:

```
silverstripe/securityreport               1.0.10 

silverstripe/framework                    3.6.5   
silverstripe/cms                          3.6.5 
```

**Comment by robbieaverill** [comment]
This _is_ a loss of functionality, but the last visited column was part of the Member object and removed in SS 4.0.

We could re-implement this - it could either be added into `MemberReportExtension` (which is applied to Member) or it could be added as a feature to cwp/cwp-core.

Thoughts @tractorcow?

**Comment by tractorcow** [comment]
It could be calculated from `LoginAttempt` couldn't it?

**Comment by tractorcow** [comment]
Just sneakily rename column from "last visited" to "last logged in".

**Comment by NightJar** [comment]
```
 * This behaviour is disabled by default.
[...]
class LoginAttempt [...]
```
The docblock warning appears to hold true.
What to do in this case? Change the column content message phrasing from `never` to `indeterminable`?

Any further suggestions @tractorcow, @robbieaverill ?

Is it reasonable to have the module enable it, or should it remain optional?
If it remains optional, should `recipe-reporting-tools` then enable it by default?

**Comment by robbieaverill** [comment]
>Is it reasonable to have the module enable it, or should it remain optional?

It might be reasonable for CWP to enable it, but not this module (IMO) or the recipe, which should be reporting only.

Can we include the column if the data is available/functionality is enabled?

**Comment by NightJar** [comment]
Yeah, I'll alter the resolution to focus on conditional inclusion. Thanks :)
