### ISSUE TITLE
Permissions report column for subsites is at the start instead of the end

### ISSUE THREAD

**Issue by robbieaverill** [silverstripe/silverstripe-securityreport#39]
**Version: CWP 2.2.x-dev**

![image](https://user-images.githubusercontent.com/5170590/49095683-4d780800-f269-11e8-9492-4bd3041be9a9.png)

It should be at the RHS end not the LHS

**Comment by micmania1** [comment]
@robbieaverill yep, extensions should have the least priority. The config for these should be set in YAML rather than the extension.

**Comment by robbieaverill** [comment]
Still an issue

**Comment by robbieaverill** [comment]
Pull requests at https://github.com/silverstripe/silverstripe-securityreport/pull/40 and https://github.com/silverstripe/silverstripe-securityreport/pull/41
