### ISSUE TITLE
TODO: Update Unit tests. Pre-fill the report with fixture-defined users.

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-securityreport#68]
## Description
Update UserSecurityReportTest::setUp() to support pre-filling the report with fixture-defined users. 

See: https://github.com/silverstripe/silverstripe-securityreport/blob/de1a170dd8546e2c15d3ad31145e03de23018480/tests/php/UserSecurityReportTest.php#L45

**Comment by GuySartorelli** [comment]
Gonna close this one - there's a test to ensure the records array isn't empty and that hasn't ever failed to my knowledge so it seems to be working fine. Fixtures would be cleaner but this isn't worth our time IMO.
