### ISSUE TITLE
TODO: Investigate should GridFieldComponents change behaviour based on whether others are available in the config

### ISSUE THREAD

**Issue by sabina-talipova** [silverstripe/silverstripe-securityreport#69]
## Description
GridFieldExportReportButton::generateExportFileData(): Investigate should GridFieldComponents change behaviour based on whether others are available in the config.
See: https://github.com/silverstripe/silverstripe-securityreport/blob/de1a170dd8546e2c15d3ad31145e03de23018480/src/Forms/GridFieldExportReportButton.php#L63

**Comment by GuySartorelli** [comment]
Gonna close this one - it's been working fine and any change to this would likely be part of a wider review of `GridField` itself. For now there's not much (if any) value looking at this one usage.
